install:
  - bundle install
  - nvm install && nvm use
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
  - npm ci
matrix:
  include:
    - os: osx
      language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
      script:
        - './android/gradlew assembleRelease -p android/'
    - os: osx
      osx_image: xcode10
      before_install:
        - brew install jq
        - bundle install
      script:
        - bundle exec fastlane ios test
