install:
  - bundle install
  - brew install watchman,
  - npm install
  - npm ci
  before_script:
    - npm test
    - (npm start > packager.log 2>&1 &) && echo $! > packager.pid
  before_install:
    - brew update
    - brew reinstall xctool
matrix:
  include:
    - os: osx
      language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
      script:
        - './android/gradlew assembleRelease -p android/'
    - os: osx
      language: swift
      osx_image: xcode10
      before_install:
        - brew install jq
        - bundle install
      script:
        - bundle exec fastlane ios test
