# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Pods for BeerXP
target 'BeerXP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Performance', '~> 5.11.0'
  
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'

  pod 'FBSDKLoginKit'
  pod 'FacebookSDK'
  
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'BeerXPTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Pods for BeerXP-tvOS
target 'BeerXP-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  

  target 'BeerXP-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
