# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Pods for BeerXP
target 'BeerXP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'

  target 'BeerXPTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Pods for BeerXP-tvOS
target 'BeerXP-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  

  target 'BeerXP-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
