# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

ENV["CRASHLYTICS_API_TOKEN"] = "123abc"
ENV["CRASHLYTICS_BUILD_SECRET"] = "secret_key"

before_all do
#  update_fastlane
  yarn(
      command: "install",
      package_path: "./package.json"
  )
#    ensure_git_branch
#    ensure_git_status_clean
#    git_pull
end

platform :ios do
  # iOS Lanes
  lane :tests do
    notification(subtitle: "Testing", message: "Executando testes")

    run_tests(project: "ios/BeerXP.xcodeproj", scheme: "BeerXP", devices: ["iPhone 6s", "iPad Air"],
      slack_url: "https://hooks.slack.com/services/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", 
      slack_channel: "#ios_build")

      notification(subtitle: "Finished", message: "Executado")
    end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
#    match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
#    match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
  end

end

platform :android do
  # Android Lanes
  before_all do
    ANDROID_VERSION_NAME = get_version_name(
            gradle_file_path:"android/app/build.gradle",
            ext_constant_name:"versionName"
    )
    ANDROID_VERSION_CODE = get_version_code(
        gradle_file_path:"android/app/build.gradle",
        ext_constant_name:"versionCode"
    )
  end

  desc "Runs all the tests"
  lane :tests do
    gradle(task: 'test', project_dir: 'android/')
  end

  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  lane :beta do
    # Generate the changelog based on commit messages since your last tag
    changelog_from_git_commits

    # Adjust the 'build_type' and 'flavor' params as needed to build the right APK for your setup
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    add_badge(
      shield: "Version-#{ANDROID_VERSION_NAME}-blue",
      dark: true,
      glob: "/android/app/src/main/res/mipmap-*/ic_launcher.png",
      shield_scale: "0.75"
    )
    # ...
  end

end